from fpdf import FPDF
from datetime import datetime
import os

class MedicalReport(FPDF):
    def header(self):
        self.set_fill_color(15, 15, 26)
        self.rect(0, 0, 210, 40, 'F')
        self.set_font('Helvetica', 'B', 22)
        self.set_text_color(102, 126, 234)
        self.cell(0, 15, '', ln=True)
        self.cell(0, 15, 'MediPredict AI - Medical Risk Report', align='C', ln=True)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'Generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}',
                  align='C', ln=True)
        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10,
            'DISCLAIMER: This report is generated by AI for educational purposes only. '
            'Always consult a licensed medical professional.',
            align='C')

    def section_title(self, title, color=(102, 126, 234)):
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(*color)
        self.set_fill_color(20, 30, 50)
        self.cell(0, 10, f'  {title}', ln=True, fill=True)
        self.ln(2)

    def info_row(self, label, value, highlight=False):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(180, 180, 180)
        self.cell(70, 8, f'  {label}:', border=0)
        self.set_font('Helvetica', '', 10)
        if highlight:
            self.set_text_color(255, 100, 100) if 'HIGH' in str(value) \
                else self.set_text_color(0, 220, 120)
        else:
            self.set_text_color(220, 220, 220)
        self.cell(0, 8, str(value), ln=True)
        self.set_draw_color(40, 40, 60)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(1)


def generate_report(patient_name, username, disease, result,
                    confidence, risk_factors, inputs_dict):
    pdf = MedicalReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_margins(10, 10, 10)

    # ── Patient Info ─────────────────────────────────
    pdf.section_title('Patient Information')
    pdf.info_row('Patient Name', patient_name)
    pdf.info_row('Account',      username)
    pdf.info_row('Report Date',  datetime.now().strftime('%Y-%m-%d'))
    pdf.info_row('Disease Screened', disease)
    pdf.ln(5)

    # ── Prediction Result ─────────────────────────────
    pdf.section_title('Prediction Result',
                       color=(255, 80, 80) if 'HIGH' in result else (0, 200, 100))
    pdf.info_row('Risk Level',   result,      highlight=True)
    pdf.info_row('AI Confidence', confidence)
    pdf.ln(5)

    # ── Input Parameters ──────────────────────────────
    pdf.section_title('Input Parameters Provided')
    for k, v in inputs_dict.items():
        pdf.info_row(k, v)
    pdf.ln(5)

    # ── Risk Factors & Recommendations ───────────────
    pdf.section_title('Key Risk Factors & Recommendations')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(200, 200, 200)
    for i, factor in enumerate(risk_factors, 1):
        pdf.cell(0, 8, f'  {i}. {factor}', ln=True)
    pdf.ln(5)

    # ── General Advice ────────────────────────────────
    pdf.section_title('General Health Advice')
    advice = [
        'Maintain a balanced diet rich in fruits and vegetables.',
        'Exercise regularly — at least 30 minutes, 5 days a week.',
        'Stay hydrated and avoid smoking/alcohol.',
        'Monitor your vitals regularly with a certified physician.',
        'Follow up on this report with your doctor immediately.'
    ]
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(200, 200, 200)
    for tip in advice:
        pdf.cell(0, 8, f'  • {tip}', ln=True)

    # ── Save ──────────────────────────────────────────
    filename = f"report_{username}_{disease.replace(' ','_')}.pdf"
    pdf.output(filename)
    return filename